### PR TITLE
Add Components

### PR DESCRIPTION
**Pull request by KayLemba**
In this project I added the following using React:

- Add components
- Add Calculator User Interface
- Add Calculator.css file

### CODE REVIEW

**Review by hiromataba — CHANGES_REQUESTED** [review]
Hi @KayLemba :wave: , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight :champagne: :tada: 
- No linter errors :heavy_check_mark: 
- Your PR has a proper description and title :+1: 
- Your design looks pretty good, Keep rocking :rocket: 

## Required Changes ♻️

- [ ] Please remove the images and icons in your `public` directory because you are not going to need them :wink: 

- [ ] Right now you have the dummy `CRA` README template. Let's try to write more descriptive documentation in our README. I would suggest you  add instructions on how users can install packages (`npm install`)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [x] [OPTIONAL] Kindly add the screenshot of your Calculator in your README file to make it look professional 

- [x] [OPTIONAL] You can use have a look a [This](https://github.com/hiromataba/Math-Magicians/blob/refactorWithHooks/README.md) to update your README file

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KayLemba** [comment]
Thank you @hiromataba

**Comment by KayLemba** [comment]
Hello @hiromataba  I have made the requested changes. Thank you .

**Review by dasileker — APPROVED** [review]
## **Hi @KayLemba ,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KayLemba** [comment]
Thank you @desileker

**Pull request merged**
